name: RFC XML Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt-get install aspell cmake python3 python3-pip python3-setuptools python3-wheel ruby xmlstarlet yajl-tools
        sudo pip3 install xml2rfc
        sudo gem install cddl
    - name: xml2rfc
      run: |
        mkdir -p spec/build
        (cd spec/build && cmake ..)
        cmake --build spec/build -v
    - uses: actions/upload-artifact@v2
      with:
        name: spec
        path: |
          spec/build/draft-*.html
          spec/build/draft-*.txt
          spec/build/misspelling.txt
          spec/build/*errors.txt
